### ISSUE TITLE
[RFC] Adjust activity tags to correspond OTEL specification

### ISSUE THREAD

**Issue by mishamyte** [jbogard/MongoDB.Driver.Core.Extensions.DiagnosticSources#16]
Hello @jbogard,
Just reviewed current version of OTEL spec and found that some tags, set by this lib are outdated. 

So I propose to discuss next changes. Will be happy to make a PR after founding a concern.

|      **Tag**     |                                                             **Problem**                                                             |               **Proposal**               |                                                             **Spec reference**                                                            |
|:----------------:|:-----------------------------------------------------------------------------------------------------------------------------------:|:----------------------------------------:|:-----------------------------------------------------------------------------------------------------------------------------------------:|
| db.user          | Now crafted as a part of connection string with address + port. It doesn't correspond spec and this data is covered by another tags | Delete tag                               | https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/database.md#mongodb      |
| net.peer.ip      | Doesn't exists                                                                                                                      | Rename tag to net.sock.peer.addr         | https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md          |
| net.transport    | Doesn't exists                                                                                                                      | Set to ip_tcp value                      | https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md          |
| otel.status_code | Doesn't respect case                                                                                                                | Adjust case to upper                     | https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/mapping-to-non-otlp.md#span-status           |
| error.type       | Doesn't exists                                                                                                                      | Use exception.type tag                   | https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/exceptions.md#attributes |
| error.msg        | Doesn't exists                                                                                                                      | Use exception.message tag                | https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/exceptions.md#attributes |
| error.stack      | Doesn't exists                                                                                                                      | Use exception.stacktrace tag             | https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/exceptions.md#attributes |
| db.connection_id | Custom tag, used by .NET's instrumentation libs for SQL drivers                                                                     | Add it with property value of @event.ConnectionId |                                                                                                                                           |

**Comment by mishamyte** [comment]
@jbogard hello, any thoughts for this?

**Comment by jbogard** [comment]
Works for me!

**Comment by jbogard** [comment]
Fixed by #18
