### ISSUE TITLE
Activity for an async mongo command is not stopped

### ISSUE THREAD

**Issue by dgrozenok** [jbogard/MongoDB.Driver.Core.Extensions.DiagnosticSources#2]
When the async command is executed in Mongo driver, the async flow is not properly followed and in the command succeeded handler the Activity.Current is not the activity started in the command started handler. If before calling the

https://github.com/jbogard/MongoDB.Driver.Core.Extensions.DiagnosticSources/blob/7c55584114c12dc431074b2d375211b760bf557a/src/MongoDB.Driver.Core.Extensions.DiagnosticSources/DiagnosticsActivityEventSubscriber.cs#L45

I add the

`Activity.Current = activity;`

it fixes the problem, but I'm not sure what consequences that could cause as I'm not familiar with the API yet.

**Comment by jbogard** [comment]
Should be fixed by #5

**Comment by dgrozenok** [comment]
Thank you!
