### ISSUE TITLE
Updating MongoDB.Driver from 2.30 -> 3.0.0 breaks the implementation

### ISSUE THREAD

**Issue by stefanolsenn** [jbogard/MongoDB.Driver.Core.Extensions.DiagnosticSources#40]
Hi. I'm having a little trouble while upgrading the MongoDB.Driver from 2.30 to 3.0 in my project.

This is my implementation
```c#
var clientSettings = MongoClientSettings.FromConnectionString(config.GetConnectionString("connection-string"));
clientSettings.ClusterConfigurator = cb => cb.Subscribe(new DiagnosticsActivityEventSubscriber(new InstrumentationOptions()
{
    CaptureCommandText = true
}));
var client = new MongoClient(clientSettings);
``` 
After upgrading the `MongoDB.Driver` to 3.0.0 my IDE complains about the parameter type
![image](https://github.com/user-attachments/assets/43a74a78-58b0-464f-9adf-5ca5a6edf17e)

As per their release notes to v3.0.0, they state that they have removed the reference to `MongoDB.Driver.Core`, and moved the content elsewhere. Issue here: https://jira.mongodb.org/browse/CSHARP-5211

Will the fix be that this package could depend on the `MongoDB.Driver`, instead of the `MongoDB.Driver.Core`? I'm happy to help and make a PR for it :+1:

**Comment by paulomorgado** [comment]
Either way, `MongoDB.Driver.Core.Extensions.DiagnosticSources` is locked to bellow version 3.0.0.

**Comment by jbogard** [comment]
I'm creating a 2.0.0 release given the dependencies also bumped.
