### ISSUE TITLE
Some spans are not useful

### ISSUE THREAD

**Issue by jamiegs** [jbogard/MongoDB.Driver.Core.Extensions.DiagnosticSources#8]
The c# mongo library is often running the commands to check on the status of the cluster. These will create single span traces which are not very useful

the traces that get created are:
mongodb.ismaster
mongodb.getlasterror
mongodb.buildinfo

It would be great if there was an option to not create activities for these commands.

**Comment by jbogard** [comment]
Is there anything on the events that makes it easy to see which ones are these internal commands?
